# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
  auto_detect_solc = false
  bytecode_hash = "none"
  evm_version = "shanghai"
  fuzz = { runs = 1_000 }
  gas_reports = ["*"]
  optimizer = true
  optimizer_runs = 10_000
  out = "out"
  script = "script"
  solc = "0.8.30"
  src = "src"
  test = "tests"
  via_ir = true
  
  extra_output = ["storageLayout"]
  extra_output_files = ["storageLayout"]
  fs_permissions = [{ access = "read-write", path = "./" }]
  remappings = [
    "solady/=node_modules/solady/src/",
    "forge-std/=node_modules/forge-std/src/",
  ]

[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 4

[etherscan]
  mainnet = { key = "${API_KEY_ETHERSCAN}" }
  hyper_evm_testnet = { key = "${API_KEY_ETHERSCAN}" }

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  arbitrum = "https://arbitrum-one-rpc.publicnode.com"
  avalanche = "https://avalanche-c-chain-rpc.publicnode.com"
  base = "https://mainnet.base.org"
  bnb_smart_chain = "https://bsc-dataseed.binance.org"
  gnosis_chain = "https://rpc.gnosischain.com"
  localhost = "http://localhost:8545"
  mainnet = "https://eth-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  optimism = "https://optimism-rpc.publicnode.com"
  polygon = "https://polygon-bor-rpc.publicnode.com"
  sepolia = "https://ethereum-sepolia-rpc.publicnode.com"
  hyper_evm_testnet = "https://rpc.hyperliquid-testnet.xyz/evm"
  hyper_evm = ""


